package rms;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.awt.event.ActionListener;
public class Restaurant extends javax.swing.JFrame implements ActionListener {
JLabel title;
JButton employee,items,selling,logout;
JPanel mainpanel,panelnorth,panelwest;
    public Restaurant() {
initComponents();
mainpanel = new JPanel(new FlowLayout(FlowLayout.CENTER));
mainpanel.setLayout(new BorderLayout());
panelnorth = new JPanel(new FlowLayout(FlowLayout.CENTER, 1, 0));
title = new JLabel("RESTAURANT MANAGEMENT SYSTEM");
title.setFont(new Font("Times New Roman", Font.BOLD, 35));
panelnorth.setPreferredSize(new Dimension(1000, 60));
panelnorth.add(title);
panelnorth.setBackground(Color.orange);
panelwest =new JPanel(new GridLayout(4, 0, 10, 10));
panelwest.setBackground(Color.blue);
panelwest.setPreferredSize(new Dimension(100, 640));
mainpanel.add(panelnorth, BorderLayout.NORTH);
mainpanel.add(panelwest, BorderLayout.WEST);
        items=new JButton("AddItem");
        items.setFont(new Font("Times New Roman", Font.BOLD, 14));
        employee=new JButton("AddEmployee");
        employee.setFont(new Font("Times New Roman", Font.BOLD, 14));
        selling=new JButton("SellMenu");
        selling.setFont(new Font("Times New Roman", Font.BOLD, 14));
   
        logout=new JButton("Logout");
        logout.setFont(new Font("Times New Roman", Font.BOLD, 14));
     
        panelwest.add(employee);

            panelwest.add(items);
                  
             panelwest.add(selling);

                               panelwest.add(logout);
//////////////////////////////////////////
 employee.addActionListener(this);
 items.addActionListener(this);
 selling.addActionListener(this);
 logout.addActionListener(this);
 /////////////////////////////////////////
add(mainpanel,BorderLayout.CENTER);
setContentPane(mainpanel);
setSize(1000,700);
setTitle("Restaurant Management System"); 
setVisible(true);
setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
validate();
repaint();         
    }        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
                new Restaurant().setVisible(false);
            }
        });
    }
    @Override
  public void actionPerformed(ActionEvent e) {
   if(e.getSource()==employee){
   new Employee().setVisible(true);
   }
  else if(e.getSource()==items){
   new PurchasedItem().setVisible(true);
   } 
  else if(e.getSource()==selling){
   new SellingItem().setVisible(true);
   } 
  else if(e.getSource()==logout){
   new login().setVisible(true);
   new Restaurant().setVisible(false);
      new Employee().setVisible(false);
         new PurchasedItem().setVisible(false);
            new SellingItem().setVisible(false); 
               setVisible(false);
   } 
                    
  }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
